app:
  host_url: "https://open-platform-migration.service.tietoevry.com"
  port: "8081"
  api_endpoint: "https://open-platform-migration.service.tietoevry.com"
ingress:
  annotation:
    nginx.ingress.kubernetes.io/force-ssl-redirect="true"
  className: "nginx"
  tls:
    - secretName: spine-tls-secret
      hosts:
        - open-platform-migration.service.tietoevry.com
  hosts:
  - host: open-platform-migration.service.tietoevry.com
    paths:
    - path: /observation-minimal
      pathType: ImplementationSpecific